# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "server" do |server|
    server.vm.provider :virtualbox do |v|
      v.memory = 4096
      v.cpus = 2
    end

    server.vm.network "forwarded_port", guest: 80, host: 8080
    server.vm.box = "jborean93/WindowsServer2012R2"
  end
end
